[profile.default]
src = 'src'
out = 'out'
libs = ["node_modules", "lib"]
remappings = []
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
polygon="${POLYGON_NODE_URL}"
mumbai="${MUMBAI_NODE_URL}"
local="${LOCAL_URL}$"

[fmt]
tab_width=2
int_types="short"
number_underscores="thousands"